server:
  address: "0.0.0.0:32010"
  max_connections: 100

database:
  dsn: "duckdb://:memory:"
  max_open_conns: 32
  health_check_period: "30s"

logging:
  level: "info"
  format: "json"

metrics:
  enabled: true
  endpoint: ":9090"

tracing:
  enabled: false

auth:
  enabled: false

reflection:
  enabled: true
