server:
  address: "0.0.0.0:32010"
  max_connections: 100
  max_message_size: 16777216
  query_timeout: "5m"
  shutdown_timeout: "30s"
  reflection: true

database:
  dsn: "duckdb://:memory:"
  max_open_conns: 100
  max_idle_conns: 50
  conn_max_lifetime: "30s"
  conn_max_idle_time: "15s"
  health_check_period: "60s"

logging:
  level: "info"
  format: "json"

metrics:
  enabled: true
  endpoint: ":9090"
  prometheus:
    enabled: true

cache:
  enabled: true
  max_size: "1GB"
  ttl: "1h"

# Enterprise features
enterprise:
  circuit_breaker:
    enabled: false
  retry:
    enabled: false
  monitoring:
    health_checks: true
    performance_tracking: true
  
# Authentication disabled for benchmarking
auth:
  enabled: false
  type: "oauth2"
  oauth2_auth:
    client_id: "enterprise-client"
    client_secret: "enterprise-secret"
    allowed_redirect_uris:
      - "https://enterprise.example.com/oauth/callback"
      - "https://admin.example.com/auth/callback"
    authorize_endpoint: "/oauth2/authorize"
    token_endpoint: "/oauth2/token"
    scopes: ["read", "write", "admin"]
    access_token_ttl: 1h
    refresh_token_ttl: 24h
    allowed_grant_types:
      - "authorization_code"
      - "refresh_token"
      - "client_credentials" 